#!/bin/bash

set -e

# Install silver
git clone https://github.com/melt-umn/silver.git
cd silver
./fetch-jars
./support/bin/install-silver-bin
cd ..

# Build the jar
./build

# Install pandoc
sudo apt install pandoc
