#!/bin/bash

set -e

# Install silver, if not installed yet
if [[ ! -x "$(command -v silver)" ]]
then
    rm -rf silver
    git clone https://github.com/melt-umn/silver.git
    cd silver
    ./fetch-jars
    ./support/bin/install-silver-bin
    cd ..
fi

# Build the jar
./build

# Install pandoc, if not installed yet
if [[ ! -x "$(command -v pandoc)" ]]
then
    sudo apt install pandoc
fi
