#!/bin/bash

# Treat all arguments up to the first optional argument as formulas, store them
# in an array
FORMULAS=()
while [[ $# -gt 0 ]] && [[ $1 != -* ]]
do
    FORMULAS+=("$1")
    shift
done

# Print help if requested
if [[ $# -eq 0 ]] || [[ $1 == "-h" ]] || [[ $1 == "--help" ]]
then
    echo "Usage: ./render [expressions] -o <file>"
    echo "Example: ./render '(a => b) & a' b -o out.pdf"
    echo "Acceptable file formats include .pdf, .tex, .html"
    echo "For more options, run pandoc --help"
    exit 0
fi

# Invoke the jar with the given formulas
if OUT=$(java -jar logic.jar "${FORMULAS[@]}")
then
    # The operation was successful, run the resulting markdown through pandoc
    # with the remaining arguments
    echo "$OUT" | pandoc $@
else
    # An error occured, print the output
    echo "$OUT"
    exit 1
fi
