#!/bin/bash

FORMULAS=()

while [[ $# -gt 0 ]] && [[ $1 != -* ]]
do
    FORMULAS+=("$1")
    shift
done

if OUT=$(java -jar logic.jar "${FORMULAS[@]}")
then
    echo "$OUT" | pandoc $@
else
    echo "$OUT"
    exit 1
fi
